[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SMTP_USER = "cream.sk09@gmail.com"
  SMTP_PASS = "frav olbs paoy stwj"
  GMAIL_APP_PASSWORD = "frav olbs paoy stwj"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/seed.json", "lib/*.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

